### ISSUE TITLE
The theme is incompleted loaded

### ISSUE THREAD

**Issue by FredAOliveira** [themefisher/parsa-hugo-personal-blog-theme#1]
I tried to build Parsa-hugo-personal-blog-theme but it is not loaded completely, as shown below:
![image](https://user-images.githubusercontent.com/44746801/58520168-fb1e9200-818c-11e9-9847-6675bf1abf0b.png)

I did not modify the template code and the only error that I could find was below shown on the browser (Chrome).

"Uncaught ReferenceError: jQuery is not defined
    at script.min.js:2"

I am begginer and I dont know where I would check to find the problem.

**Comment by Somrat37** [comment]
@FredAOliveira , as you told i download the template from here and run it on my localhost. i found no error. can you please check again? and make sure that your hugo version is minimum 0.55

**Comment by FredAOliveira** [comment]
Hello Somrat37!

Thank you for your support, I found out what was happening. The paths for the directories were wrong. I reorganizes the files and now is working properly.

**Comment by donnydark0** [comment]
How did you fix it? I am having the same issue.
