### ISSUE TITLE
Image not responsive

### ISSUE THREAD

**Issue by hervyqa** [themefisher/parsa-hugo-personal-blog-theme#2]
when I add an image on the blog page, for example ![](/image/blog/image.png it looks strange, and I have to scroll right. Desktop and on the mobile the same result.

Parsa theme & kross and maybe other theme.

Thank you.

**Comment by Somrat37** [comment]
Hey @hervyqa , thanks for your concern, i just make an update and fixed this issue, can you please download the latest code?
