### ISSUE TITLE
Featured images are not responsive

### ISSUE THREAD

**Issue by daniprol** [themefisher/parsa-hugo-personal-blog-theme#3]
I've been working with the theme for a few days. It looks great on desktop mode so far, but when you use a tablet or phone size the "featured articles" images are cut out by the header and don't feel responsive at all. 
At first I thought I messed it up when making changes to the CSS, but the theme looks to have the same problem in the demo page.
![capturapantalla](https://user-images.githubusercontent.com/53005877/64170807-58dc0d80-ce51-11e9-9d53-3ca05ee55e95.jpg)

I'm actually surprised I didn't spot this problem earlier.

Any idea on how to fix it?

**Comment by Somrat37** [comment]
@daniprol , thanks for your concern, i fixed this issue, can you please pull the latest code?

**Comment by daniprol** [comment]
It seems to work fine now. 

Thank you so much.
