### ISSUE TITLE
Jquery Error after fresh install 

### ISSUE THREAD

**Issue by Swaggadan** [themefisher/parsa-hugo-personal-blog-theme#4]
Using google chrome Inspect, there is the error below
```
script.min.js:2 Uncaught ReferenceError: jQuery is not defined
    at script.min.js:2

```
![image](https://user-images.githubusercontent.com/137142/65845874-d89eb000-e309-11e9-978f-f29c2e91566b.png)

**Comment by mkmayank** [comment]
Same error for me too

**Comment by Swaggadan** [comment]
got it, thanks
