### ISSUE TITLE
Very slow loading on mobile view

### ISSUE THREAD

**Issue by meetmarvin** [themefisher/parsa-hugo-personal-blog-theme#6]
I'm not sure if why is it loading really slow when navigating back to home page. Only happening when mobile view

Reproduction:

1. Visit demo site (https://themes.gohugo.io/theme/parsa-hugo-personal-blog-theme/) using chrome browser (not all browsers were tested)
2. Right-click then click Inspect (Ctrl+Shift+I or press  F12
3. Toggle Device Toolbar (Ctrl+Shift+M)
2. Click logo to go back to index
3. It will load very slow. (Other browsers not tested.)

## Screen capture:
![parsa](https://user-images.githubusercontent.com/12038591/66444532-0b7e3c00-eaa0-11e9-82ba-8943a37c8b2f.png)

## Video Recording:
[parsa-video-record.zip](https://github.com/themefisher/parsa-hugo-personal-blog-theme/files/3705158/parsa-video-record.zip)

**Comment by Somrat37** [comment]
please make sure your internet is working properly.

**Comment by meetmarvin** [comment]
It can confirm that I have a decent connection.

Reproduction:
Chrome browser (mobile view) refresh home page. Observe issue occurs

Firefox browser (mobile view)  refresh home page. Issue not seen.

**Comment by Somrat37** [comment]
hey @meetmarvin , we made an update, now you can check the page speed, you can also check the [google pageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fthemes.gohugo.io%2Ftheme%2Fparsa-hugo-personal-blog-theme%2F)

**Comment by meetmarvin** [comment]
@Somrat37 thank you again. I just tested it now. However, it still loads slow. I can confirm that my internet connection is fine. Please see the screen recording so you can reproduce it. Thank you!

https://ufile.io/bej91ndr

**Comment by Somrat37** [comment]
@meetmarvin , i am sorry for this issue, i made some changes again, can you please pull the latest code and check it again? thanks.

**Comment by meetmarvin** [comment]
@Somrat37 seems working fine now. See

https://ufile.io/gfp88z17

**Comment by mehedi-sharif** [comment]
@meetmarvin great , I am going to close this issue .
Thanks
